### ISSUE TITLE
Support Querying in componentDidMount instead of render

### ISSUE THREAD

**Issue by evbo** [apollographql/apollo-scalajs#19]
Hi and thanks again for the suite of react tools! Currently Query must return a ReactElement as part of a render. But what about graphql queries that need to run only to initialize state? Those should run in componentDidMount and not render.

For instance, running this can't work because state can't be set inside render wtihout triggering warnings/errors in react:

```
def render(): ReactElement = {
    Query(someQuery) {
      _.data.map { d =>
        setState(dataLoaded = true)
      
      div("state saved!")
    }.getOrElse(h1("loading!"))
    }
  }
```

results in:
```
Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
```

When I try using Query inside `componentDidMount` it appears to never make any requests.

**Comment by shadaj** [comment]
So the `Query` component is designed for use within the React rendering tree, so it won't work elsewhere. The way to get data in `componentDidMount` would be to grab your instance of `ApolloClient` and call the `query` method as described in https://www.apollographql.com/docs/scalajs/essentials/getting-started.html

**Comment by evbo** [comment]
thank you and sorry, I completely missed that point in the documentation!

**Comment by evbo** [comment]
I think one thing missing from those docs is to include an execution context:
```
implicit val executionContext = scala.concurrent.ExecutionContext.Implicits.global
```
